// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MonacoController from "./monaco_controller.js"
application.register("monaco", MonacoController)

import RemovalsController from "./removals_controller.js"
application.register("removals", RemovalsController)

import ConfettiController from "./confetti_controller.js"
application.register("confetti", ConfettiController)
